@host= https://localhost:44369

POST  {{host}}/api/Account/token
Content-Type: application/json

{
  "username":"LexisnexisAdmin@adappt.co.in",
  "password":"LonestarAdmin@123"
}


###
# {
#     "firstName":"Shafi",
#     "lastName" : "Ahmed",
#     "email" : "test@gmail.com",
#     "password" : "password"
# }